name: auto-sync-fork
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions: read-all

jobs:
  auto-sync-fork:
    name: Sync fork
    runs-on: ubuntu-latest
    steps:
      - name: "gh repo sync"
        id: gh-repo-sync
        run: gh repo sync ${{ github.repository }} -b main
        env:
          # PAT should have write access to "contents" and "workflows"
          # https://github.com/cli/cli/issues/7574
          GH_TOKEN: ${{ secrets.SYNC_TOKEN }}
      - name: "report failure"
        if: always() && steps.gh-repo-sync.outcome != 'success'
        uses: actions-ecosystem/action-create-issue@b02a3c1d9d929a5839315bd255e40389f0dab627 #v1
        with:
          github_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          title: "Unable to sync ossf-tests/scorecard-action"
          body: |
            Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          repo: "ossf/scorecard-action"
          labels: |
            e2e
            automated-tests
