name: scorecard-workflow-dispatch
on:
  schedule:
    - cron: '0 2 * * *'

# Declare default permissions as read only.
jobs:
  scorecard-workflow-dispatch:
    name: Scorecard ${{ matrix.type }} workflow dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [bash, golang]
    steps:
      - name: "workflow dispatch"
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.SCORECARD_READ_TOKEN }}"
          https://api.github.com/repos/ossf-tests/scorecard-action/actions/workflows/scorecards-${{ matrix.type }}.yml/dispatches
          -d '{"ref":"main"}'
  report-failed-run:
    runs-on: ubuntu-latest
    needs: [scorecard-workflow-dispatch]
    if: needs.analysis.result == 'failure'
    steps:
      - uses: actions-ecosystem/action-create-issue@b02a3c1d9d929a5839315bd255e40389f0dab627 #v1
        with:
          github_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          title: "Failing e2e tests - scorecard-workflow-dispatch on ${{ github.repository }}"
          body: |
            Repo: https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_REF_NAME
            Run: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
            Workflow name: $GITHUB_WORKFLOW
            Workflow file: https://github.com/$GITHUB_REPOSITORY/tree/main/.github/workflows/scorecards-workflow-dispatch.yml
            Trigger: $GITHUB_EVENT_NAME
            Branch: $GITHUB_REF_NAME
          repo: "ossf/scorecard-action"
          labels: |
            e2e
            automated-tests
