name: Scorecards supply-chain security
on:
  workflow_dispatch:
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]

# Declare default permissions as read only.

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        with:
          persist-credentials: false

      - name: "workflow dispatch"
        shell: bash
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/ossf-tests/scorecard-action/actions/workflows/scorecards.yml/dispatches \
             -d '{"ref":"main"}' \
             -H "Authorization: token ${{ secrets.SCORECARD_READ_TOKEN }}"
  run-if-failed:
    runs-on: ubuntu-latest
    needs: [analysis]
    if: always() && (needs.analysis.result == 'failure')
    steps:
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: '1.17'
      - name: Create GitHub Issue
        run: |
         go env -w GOFLAGS=-mod=mod
         go install github.com/naveensrinivasan/Create-GitHub-Issue@22673baa793380281a4346e8defab7f367035a10
         Create-GitHub-Issue ossf scorecard-action ${{ secrets.SCORECARD_TOKEN }} "Failed to run automated scorecard workflow dispatch@main ${{ github.repository }}" "e2e,automated-tests" "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
